export const students = [
  { id: "s1", name: "Rahul Sharma", skills: ["React", "Node.js", "Python"], gpa: 8.5, college: "Delhi University" },
  { id: "s2", name: "Priya Patel", skills: ["Java", "Machine Learning", "SQL"], gpa: 9.1, college: "IIT Bombay" },
  { id: "s3", name: "Amit Kumar", skills: ["C++", "Spring Boot", "AWS"], gpa: 8.2, college: "NIT Trichy" },
  { id: "s4", name: "Sneha Reddy", skills: ["UI/UX", "Figma", "Tailwind"], gpa: 8.8, college: "NID Bangalore" },
  { id: "s5", name: "Vikram Singh", skills: ["Angular", "Docker", "Kubernetes"], gpa: 7.9, college: "BITS Pilani" }
];

export const employers = [
  { id: "e1", name: "TechNova Solutions", industry: "IT Services", size: "1000-5000", location: "Bangalore" },
  { id: "e2", name: "Innovate AI", industry: "Artificial Intelligence", size: "50-200", location: "Hyderabad" },
  { id: "e3", name: "Global Finance Corp", industry: "Fintech", size: "10000+", location: "Mumbai" },
  { id: "e4", name: "EduTech India", industry: "EdTech", size: "200-500", location: "Pune" },
  { id: "e5", name: "HealthCare Systems", industry: "HealthTech", size: "500-1000", location: "Delhi" }
];

export type Job = {
  id: string;
  title: string;
  company: string;
  location: string;
  salary: string;
  type: string;
  description: string;
  requiredSkills: string[];
  category: "private" | "government";
  source: string;
  sourceUrl: string;
  logo?: string;
  lastDate?: string;
  vacancies?: number;
};

export const jobs: Job[] = [
  // ── PRIVATE JOBS (from LinkedIn / official company career pages) ────────────
  {
    id: "p1",
    title: "Software Engineer",
    company: "Tata Consultancy Services (TCS)",
    location: "Bangalore / Mumbai / Chennai",
    salary: "₹7L – ₹12L",
    type: "Full-time",
    description: "Join TCS as a Software Engineer. Work on large-scale enterprise solutions across BFSI, retail, and manufacturing domains.",
    requiredSkills: ["Java", "Spring Boot", "SQL", "REST APIs"],
    category: "private",
    source: "LinkedIn & TCS Careers",
    sourceUrl: "https://www.tcs.com/careers",
  },
  {
    id: "p2",
    title: "Systems Engineer",
    company: "Infosys",
    location: "Pune / Hyderabad / Bangalore",
    salary: "₹6.5L – ₹10L",
    type: "Full-time",
    description: "Infosys Systems Engineer program for fresh graduates. Rotational roles in Java, Python, and cloud platforms.",
    requiredSkills: ["Python", "Java", "Cloud Basics", "Agile"],
    category: "private",
    source: "LinkedIn & Infosys Careers",
    sourceUrl: "https://www.infosys.com/careers/",
  },
  {
    id: "p3",
    title: "Software Developer",
    company: "Wipro",
    location: "Multiple Cities",
    salary: "₹6L – ₹9.5L",
    type: "Full-time",
    description: "Wipro NLTH (National Level Talent Hunt) for fresh graduates. Engineering roles across digital and cloud divisions.",
    requiredSkills: ["JavaScript", "Node.js", "MySQL", "Docker"],
    category: "private",
    source: "LinkedIn & Wipro Careers",
    sourceUrl: "https://careers.wipro.com/",
  },
  {
    id: "p4",
    title: "Associate Software Engineer",
    company: "HCLTech",
    location: "Noida / Hyderabad",
    salary: "₹6.5L – ₹11L",
    type: "Full-time",
    description: "HCLTech is hiring ASEs for digital transformation projects. Work with global clients on cutting-edge technology.",
    requiredSkills: ["React", "Angular", "TypeScript", "CI/CD"],
    category: "private",
    source: "LinkedIn & HCLTech Careers",
    sourceUrl: "https://www.hcltech.com/careers",
  },
  {
    id: "p5",
    title: "Software Engineer – India",
    company: "Google India",
    location: "Bangalore / Hyderabad",
    salary: "₹25L – ₹50L",
    type: "Full-time",
    description: "Google India is seeking passionate engineers to build products used by billions. Strong DSA and system design skills required.",
    requiredSkills: ["C++", "Python", "System Design", "Algorithms"],
    category: "private",
    source: "LinkedIn & Google Careers",
    sourceUrl: "https://careers.google.com/jobs/results/?location=India",
  },
  {
    id: "p6",
    title: "SDE-1 (Software Development Engineer)",
    company: "Amazon India",
    location: "Bangalore / Hyderabad",
    salary: "₹20L – ₹40L",
    type: "Full-time",
    description: "Amazon is hiring SDE-1 engineers across AWS, Alexa, and retail divisions. High ownership, high impact roles.",
    requiredSkills: ["Java", "Python", "DSA", "System Design"],
    category: "private",
    source: "LinkedIn & Amazon Jobs",
    sourceUrl: "https://www.amazon.jobs/en/locations/india",
  },
  {
    id: "p7",
    title: "Software Engineer 2",
    company: "Microsoft India",
    location: "Hyderabad / Bangalore",
    salary: "₹22L – ₹45L",
    type: "Full-time",
    description: "Microsoft India is building next-gen AI-powered products. Join teams working on Azure, Office 365, and LinkedIn.",
    requiredSkills: ["C#", ".NET", "Azure", "TypeScript"],
    category: "private",
    source: "LinkedIn & Microsoft Careers",
    sourceUrl: "https://careers.microsoft.com/v2/global/en/jobs.html?l=India",
  },
  {
    id: "p8",
    title: "Senior Software Engineer",
    company: "Flipkart",
    location: "Bangalore",
    salary: "₹18L – ₹35L",
    type: "Full-time",
    description: "Flipkart is India's leading e-commerce platform. Join engineering teams building scalable, high-traffic systems.",
    requiredSkills: ["Go", "Kafka", "Microservices", "PostgreSQL"],
    category: "private",
    source: "LinkedIn & Flipkart Careers",
    sourceUrl: "https://www.flipkartcareers.com/#!/",
  },
  {
    id: "p9",
    title: "Software Development Engineer",
    company: "Swiggy",
    location: "Bangalore",
    salary: "₹15L – ₹30L",
    type: "Full-time",
    description: "Swiggy is building the future of food delivery and quick commerce. Engineering roles in backend, frontend, and data.",
    requiredSkills: ["Python", "Golang", "React", "Redis"],
    category: "private",
    source: "LinkedIn & Swiggy Careers",
    sourceUrl: "https://careers.swiggy.com/",
  },
  {
    id: "p10",
    title: "Member of Technical Staff",
    company: "Zomato",
    location: "Gurugram / Bangalore",
    salary: "₹14L – ₹28L",
    type: "Full-time",
    description: "Zomato is hiring engineers for its hyper-scale platforms serving 10M+ orders per day. High-growth environment.",
    requiredSkills: ["PHP", "React", "Kotlin", "AWS"],
    category: "private",
    source: "LinkedIn & Zomato Careers",
    sourceUrl: "https://www.zomato.com/careers",
  },
  {
    id: "p11",
    title: "Data Scientist",
    company: "BYJU'S (Think & Learn Pvt Ltd)",
    location: "Bangalore / Remote",
    salary: "₹12L – ₹22L",
    type: "Full-time",
    description: "BYJU'S is looking for Data Scientists to personalise learning experiences using ML and AI for millions of students.",
    requiredSkills: ["Python", "TensorFlow", "NLP", "SQL"],
    category: "private",
    source: "LinkedIn & BYJU'S Careers",
    sourceUrl: "https://byjus.com/careers/",
  },
  {
    id: "p12",
    title: "Software Engineer Intern",
    company: "Razorpay",
    location: "Bangalore (Remote Option)",
    salary: "₹40K – ₹60K/month",
    type: "Internship",
    description: "Razorpay summer internship for engineering students. Work on India's leading payments infrastructure platform.",
    requiredSkills: ["JavaScript", "Node.js", "React", "Databases"],
    category: "private",
    source: "LinkedIn & Razorpay Careers",
    sourceUrl: "https://razorpay.com/jobs/",
  },

  // ── GOVERNMENT JOBS (from official Indian government portals) ───────────────
  {
    id: "g1",
    title: "Combined Graduate Level (CGL) – Assistant Section Officer",
    company: "Staff Selection Commission (SSC)",
    location: "All India",
    salary: "₹44,900 – ₹1,42,400 (Level 8)",
    type: "Full-time",
    description: "SSC CGL 2025-26 notification for Group B & C posts in various Ministries, Departments and Organisations of the Government of India.",
    requiredSkills: ["General Intelligence", "English", "Quantitative Aptitude", "General Awareness"],
    category: "government",
    source: "SSC Official Portal",
    sourceUrl: "https://ssc.nic.in/",
    lastDate: "31 Jul 2026",
    vacancies: 17727,
  },
  {
    id: "g2",
    title: "Civil Services Examination – IAS / IPS / IFS",
    company: "Union Public Service Commission (UPSC)",
    location: "All India",
    salary: "₹56,100 – ₹2,50,000 (Level 10 and above)",
    type: "Full-time",
    description: "UPSC Civil Services Exam 2025 for recruitment to IAS, IPS, IFS and other Group A & B Central Services.",
    requiredSkills: ["General Studies", "Optional Subject", "Essay", "Current Affairs"],
    category: "government",
    source: "UPSC Official Website",
    sourceUrl: "https://upsc.gov.in/",
    lastDate: "20 May 2026",
    vacancies: 1056,
  },
  {
    id: "g3",
    title: "RRB NTPC – Junior Clerk cum Typist / Station Master",
    company: "Railway Recruitment Boards (RRB) – Indian Railways",
    location: "Pan India (Zonal Railways)",
    salary: "₹19,900 – ₹63,200",
    type: "Full-time",
    description: "RRB NTPC 2025 recruitment for Non-Technical Popular Category posts across Indian Railways zones.",
    requiredSkills: ["General Awareness", "Mathematics", "General Intelligence", "Typing (for relevant posts)"],
    category: "government",
    source: "Indian Railways – RRB Portal",
    sourceUrl: "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366,554",
    lastDate: "30 Jun 2026",
    vacancies: 11558,
  },
  {
    id: "g4",
    title: "Probationary Officer (PO)",
    company: "State Bank of India (SBI)",
    location: "All India",
    salary: "₹41,960 – ₹63,840 (with perks)",
    type: "Full-time",
    description: "SBI PO 2025 recruitment for Probationary Officers. One of the most prestigious banking jobs in India.",
    requiredSkills: ["Reasoning", "Quantitative Aptitude", "English Language", "General/Economy/Banking Awareness"],
    category: "government",
    source: "SBI Careers Portal",
    sourceUrl: "https://bank.sbi/web/careers",
    lastDate: "15 May 2026",
    vacancies: 600,
  },
  {
    id: "g5",
    title: "IBPS PO – Probationary Officer",
    company: "Institute of Banking Personnel Selection (IBPS)",
    location: "All India (Participating Banks)",
    salary: "₹36,000 – ₹63,840",
    type: "Full-time",
    description: "IBPS PO CRP-XV 2025 recruitment for Probationary Officers in various public sector banks across India.",
    requiredSkills: ["Reasoning & Computer Aptitude", "English Language", "Data Analysis", "General Economy/Banking"],
    category: "government",
    source: "IBPS Official Website",
    sourceUrl: "https://www.ibps.in/",
    lastDate: "31 Aug 2026",
    vacancies: 4455,
  },
  {
    id: "g6",
    title: "Scientist / Engineer 'SC'",
    company: "Defence Research and Development Organisation (DRDO)",
    location: "New Delhi / Hyderabad / Pune / Bangalore",
    salary: "₹56,100 – ₹1,77,500 (Level 10)",
    type: "Full-time",
    description: "DRDO recruitment for Scientist posts in Computer Science, Electronics, and Mechanical Engineering disciplines.",
    requiredSkills: ["B.E./B.Tech (CS/EC/ME)", "Research Aptitude", "GATE Score", "Technical Knowledge"],
    category: "government",
    source: "DRDO Official Website",
    sourceUrl: "https://www.drdo.gov.in/careers",
    lastDate: "30 Jun 2026",
    vacancies: 228,
  },
  {
    id: "g7",
    title: "Scientist / Engineer (Computer Science)",
    company: "Indian Space Research Organisation (ISRO)",
    location: "Bangalore / Thiruvananthapuram / Ahmedabad",
    salary: "₹56,100 – ₹1,77,500",
    type: "Full-time",
    description: "ISRO ICRB Recruitment 2025 for Scientist/Engineer SC posts. Work on India's space missions and satellite systems.",
    requiredSkills: ["B.E./B.Tech (CS/IT)", "Embedded Systems", "C/C++", "GATE Score preferred"],
    category: "government",
    source: "ISRO Official Website",
    sourceUrl: "https://www.isro.gov.in/Careers.html",
    lastDate: "15 Jul 2026",
    vacancies: 303,
  },
  {
    id: "g8",
    title: "Junior Engineer (Civil/Electrical/Mechanical)",
    company: "Central Public Works Department (CPWD)",
    location: "All India",
    salary: "₹35,400 – ₹1,12,400 (Level 6)",
    type: "Full-time",
    description: "CPWD Junior Engineer Recruitment 2025 via SSC JE exam for engineering roles in India's premier public works body.",
    requiredSkills: ["Civil/Electrical/Mechanical Engineering", "Technical Drawing", "Estimation & Costing"],
    category: "government",
    source: "SSC JE Portal",
    sourceUrl: "https://ssc.nic.in/",
    lastDate: "30 Sep 2026",
    vacancies: 1765,
  },
  {
    id: "g9",
    title: "Development Officer (IT / Computer Applications)",
    company: "National Informatics Centre (NIC)",
    location: "New Delhi / All India",
    salary: "₹47,600 – ₹1,51,100 (Level 8)",
    type: "Full-time",
    description: "NIC recruitment for IT professionals to design, develop, and manage critical e-governance infrastructure of India.",
    requiredSkills: ["B.E./B.Tech (CS/IT) or MCA", "Software Development", "Networking", "Databases"],
    category: "government",
    source: "NCS – National Career Service Portal",
    sourceUrl: "https://www.ncs.gov.in/",
    lastDate: "30 Aug 2026",
    vacancies: 127,
  },
  {
    id: "g10",
    title: "Assistant Manager (IT) – Grade A",
    company: "National Bank for Agriculture & Rural Development (NABARD)",
    location: "All India",
    salary: "₹44,500 – ₹89,150 (with allowances)",
    type: "Full-time",
    description: "NABARD Grade A recruitment 2025 for IT professionals to drive digital transformation in rural banking.",
    requiredSkills: ["B.E./B.Tech (CS/IT)", "Database Management", "Cybersecurity Basics", "NABARD/Banking Knowledge"],
    category: "government",
    source: "NABARD Official Website",
    sourceUrl: "https://www.nabard.org/career.aspx",
    lastDate: "31 May 2026",
    vacancies: 102,
  },
];

export const privateJobs = jobs.filter(j => j.category === "private");
export const governmentJobs = jobs.filter(j => j.category === "government");

export const mockAnalytics = {
  placementsByMonth: [
    { name: 'Jan', placements: 120 },
    { name: 'Feb', placements: 150 },
    { name: 'Mar', placements: 180 },
    { name: 'Apr', placements: 210 },
    { name: 'May', placements: 190 },
    { name: 'Jun', placements: 250 },
  ],
  topIndustries: [
    { name: 'IT Services', value: 45 },
    { name: 'Fintech', value: 20 },
    { name: 'EdTech', value: 15 },
    { name: 'HealthTech', value: 10 },
    { name: 'Others', value: 10 },
  ],
  skillDemand: [
    { skill: 'React', demand: 85 },
    { skill: 'Python', demand: 78 },
    { skill: 'Java', demand: 72 },
    { skill: 'AWS', demand: 65 },
    { skill: 'SQL', demand: 60 },
  ]
};
